// Generated by https://quicktype.io

export interface CharactersResponse {
  info: Info;
  data: Data[]
}

export interface Data {
  _id:         string;
  name:        string;
  description: string;
  image:       string;
  __v:         number;
}



export interface Info {
  total: number;
  page:  number;
  limit: number;
  next:  string;
  prev:  string;
}

export interface DataByCategoryAndPage{
  [key: string] : {
    page: number,
    articles: Data[]
  }
}
